#[profile.default]
#src = "src"
#out = "out"
#libs = ["lib"]
#ffi = true

# doesn't work idk why
#remapping = [
#   "@chainlink/contracts/=../lib/chainlink-brownie-contracts/contracts/src/v0.8/interfaces/AggregatorV3Interface.sol",
#]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options


#  /Users/ruhaanbhagat/foundry-23/foundry-fund-me-f23/lib/chainlink-brownie-contracts/contracts/src/v0.8/interfaces/AggregatorV3Interface.sol


[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/',
]
ffi = true
